src/app/(dashboard)/accounts/page.tsx, src/app/admin/(dashboard)/requests/(tabs)/debit.tsx, src/app/admin/(dashboard)/settings/(tabs)/logs.tsx, src/app/admin/(dashboard)/users/page.tsx
This pull request adds search functionality to several pages in the application. The search functionality allows users to search for specific items within the page, improving the overall user experience.
=> Add search functionality to other pages

src/app/admin/(dashboard)/businesses/InfoCards.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/accounts.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/directors.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/documents.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/dropzone.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/shareholder.tsx, src/app/admin/(dashboard)/businesses/[id]/page.tsx, src/app/admin/(dashboard)/businesses/accounts/[id]/TransactionStats.tsx, src/app/admin/(dashboard)/businesses/accounts/[id]/page.tsx, src/app/admin/(dashboard)/businesses/accounts/[id]/styles.module.scss, src/app/admin/(dashboard)/businesses/accounts/[id]/transactions/page.tsx, src/app/admin/(dashboard)/businesses/page.tsx, src/app/admin/(dashboard)/dashboard/page.tsx, src/lib/hooks/accounts.ts, src/lib/schema.ts, src/lib/store/transaction.ts, src/lib/utils.ts, src/ui/components/Cards/index.tsx, src/ui/components/Charts/index.tsx, src/ui/styles/business.module.scss, src/ui/styles/containedInput.module.css, src/ui/styles/singlebusiness.module.scss
This pull request includes updates to the UI for the business page, specifically for the biz docs and director tab. It also adds a new component called CardFive for displaying business information. The changes include updating the CSS for the containedInput module, refactoring the DirectorForm component to improve file upload logic, updating the account tab URL in the handleRowClick function, and refactoring the Transaction component to improve table row click functionality. Additionally, some CSS styles have been modified for various elements.
=> Update UI for business page and add CardFive component

src/app/(dashboard)/layout.tsx, src/app/(dashboard)/settings/(tabs)/keys.tsx, src/app/(dashboard)/settings/page.tsx, src/app/(dashboard)/settings/styles.module.scss, src/middleware.ts
This pull request updates the UI for the user's settings page. It includes changes to the layout, styling, and functionality of the settings page. The changes improve the user experience and make the settings page more intuitive and user-friendly.
Please review the changes and provide any feedback or suggestions. Thank you!++
=> Update UI for user's settings

src/app/(dashboard)/accounts/[id]/page.tsx, src/app/(dashboard)/accounts/[id]/transactions/page.tsx, src/app/(dashboard)/accounts/[id]/transactions/styles.module.scss, src/app/(dashboard)/accounts/page.tsx, src/app/(dashboard)/debit-requests/new/modal.tsx, src/app/(dashboard)/debit-requests/new/styles.module.scss, src/app/(dashboard)/page.tsx, src/middleware.ts
This pull request includes updates to the transaction table and debit request modal. The changes include styling updates, addition of a debit request button, and the implementation of a debit request modal. These updates improve the user experience and functionality of the application.
=> Update trx table and debit request modal

src/app/admin/(dashboard)/account-requests/page.tsx, src/lib/hooks/requests.ts
This pull request updates the account request table by adding a new dependency and a new function called `revalidate()`. The `revalidate()` function is used to fetch the accounts again after an approval or rejection action is performed. This ensures that the table is updated with the latest data.
=> Update account request table

src/app/(dashboard)/debit-requests/new/modal.tsx, src/app/admin/(dashboard)/businesses/[id]/page.tsx, src/app/admin/(dashboard)/requests/(tabs)/debit.tsx, src/app/admin/(dashboard)/requests/RequestDrawer.tsx, src/lib/hooks/requests.ts, src/ui/components/Cards/AccountCard.tsx, src/ui/components/Navbar/index.tsx, src/ui/components/Navbar/styles.module.scss, src/ui/components/SingleAccount/(tabs)/AccountDetails.tsx, src/ui/components/SingleAccount/index.tsx
Also refactored the dialog-box for activating a business
=> Pop-up dialog box for trusting business

src/app/(dashboard)/accounts/modal/index.tsx, src/app/(dashboard)/accounts/page.tsx, src/app/(dashboard)/settings/(tabs)/keys.tsx, src/ui/components/Dropzone/index.tsx
Refactored the webhook  requests with new ep
=> add supporting document when performing any action on a user request.

src/app/(dashboard)/accounts/[id]/page.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/keys.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/requests/(tabs)/access.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/requests/index.tsx
- To copy an API key before a business is activated, shows undefined
- Change "Access" to "Services" under businesses > requests
=> Single business page

src/app/(dashboard)/settings/(tabs)/keys.tsx, src/app/admin/(dashboard)/businesses/page.tsx, src/app/admin/(dashboard)/pricing-plans/drawer.tsx, src/app/admin/(dashboard)/pricing-plans/new/page.tsx, src/app/admin/(dashboard)/pricing-plans/page.tsx, src/ui/components/SelectCreatable/index.tsx, src/ui/components/SingleAccount/(tabs)/Documents.tsx, src/ui/components/SingleAccount/index.tsx, src/ui/components/TextInputWithFile/index.tsx
This pull request addresses several key enhancements and bug fixes to improve the overall user experience and functionality of our business and admin features.
Changes Included:
1.⁠ ⁠Disabled copy functionality for unavailable event hooks.
2.⁠ ⁠Removed download option for business single account documents tab.
3.⁠ ⁠Fixed email column overflow issue on admin businesses table.
4.⁠ ⁠Updated Pricing Plan drawer with actual features, including titles and descriptions.
Testing Instructions:
1.⁠ ⁠Verify that copy functionality is disabled for unavailable event hooks.
2.⁠ ⁠Confirm that download option is removed for business single account documents tab.
3.⁠ ⁠Check that email column no longer overflows into date column on admin businesses table.
4.⁠ ⁠Review Pricing Plan drawer for accurate …
=> Enhancements and Bug Fixes for Business and Admin Features

src/app/(dashboard)/payouts/PayoutDrawer.tsx, src/app/(dashboard)/transactions/drawer.tsx, src/app/admin/(dashboard)/payouts/(tabs)/PayoutTransactions/(tabs)/All.tsx, src/app/admin/(dashboard)/payouts/(tabs)/PayoutTransactions/(tabs)/Cancelled.tsx, src/app/admin/(dashboard)/payouts/(tabs)/PayoutTransactions/index.tsx, src/app/admin/(dashboard)/payouts/(tabs)/Users.tsx, src/app/admin/(dashboard)/payouts/[id]/account/page.tsx, src/app/admin/(dashboard)/requests/(tabs)/payouts/AllPayoutRequests.tsx, src/app/admin/(dashboard)/requests/(tabs)/payouts/PendingRequests.tsx, src/app/admin/(dashboard)/requests/(tabs)/payouts/drawer.tsx, src/app/admin/(dashboard)/requests/(tabs)/payouts/index.tsx, src/app/admin/(dashboard)/transactions/[accountId]/page.tsx, src/lib/hooks/accounts.ts, src/lib/hooks/requests.ts, src/lib/hooks/transactions.ts, src/ui/components/SingleAccount/index.tsx, src/ui/components/TableRows/index.tsx
Key updates to transaction management:
•⁠  ⁠Transaction drawers for enhanced user experience
•⁠  ⁠Pagination for improved performance with large datasets
•⁠  ⁠Approval and rejection logic for payout transaction requests
•⁠  ⁠Admin capability to view issued account details and transactions
=> Transaction Management Updates: Drawers, Pagination, Payout Requests, and Admin Views

src/app/admin/(dashboard)/requests/(tabs)/PayoutAccount.tsx, src/app/admin/(dashboard)/requests/tabs.tsx
•⁠  ⁠Ability for admins to approve payout account requests
•⁠  ⁠Option to reject requests.
•⁠  Separation of payout account from Account Issuance tab
=> Add Payout Account Request Approval/Rejection Functionality

src/app/(dashboard)/payouts/PayoutDrawer.tsx
This pull request refactors the PayoutDrawer component to remove a console log and to close the cancel modal when a payout transaction is successfully cancelled. The changes include removing the console log statement and adding the closeCancel() function call after setting the data in the PayoutTransactionDrawer component. These improvements enhance the cancellation experience for users.
=> Refactor PayoutDrawer to improve cancellation functionality

src/app/(dashboard)/account-requests/drawer.tsx, src/app/(dashboard)/accounts/page.tsx, src/app/(dashboard)/debit-requests/drawer.tsx, src/app/(dashboard)/users/page.tsx, src/app/admin/(dashboard)/account-requests/[id]/page.tsx, src/app/admin/(dashboard)/businesses/new/page.tsx, src/app/admin/(dashboard)/requests/drawer.tsx, src/lib/schema.ts, src/ui/components/DocumentViewer/renderPdf.tsx, src/ui/components/SelectDropdownSearch/index.tsx
This pull request includes several refactorings and bug fixes for various components in the codebase.
- The `SelectCountryDialCode` component has been refactored to update the placeholder text for better clarity.
- The `RenderPdf` component has been refactored to adjust the height of the ScrollArea for better display of PDF content.
- The `Users` page component has been refactored to improve email display and table layout.
- The `DebitRequestDrawer` and `DebitDrawer` components have been refactored. The `destDetails` in `DebitRequestDrawer` now displays the account name if available, or "N/A" otherwise. A console.log statement has been removed from `DebitDrawer`.
- The `TextInputWithFile` component has been refactored to handle null values in `selectedRequest.documentData`.
- The tab …
=> Refactor components and fix issues

package.json, src/ui/components/ErrorFallback/index.tsx, yarn.lock
Add ErrorFallback component to handle error display and refresh Update yarn.lock to include react-error-boundary package
=> Refactor package.json to add react-error-boundary dependency

src/app/admin/(dashboard)/businesses/new/page.tsx, src/lib/schema.ts
This pull request refactors the makeDirectorAShareholder function in the NewBusiness component to properly duplicate a director. It also includes changes to remove empty shareholders and check if a director already exists as a shareholder. If the director exists, the function replaces the existing director with the new one.
=> Refactor makeDirectorAShareholder function in NewBusiness

src/app/admin/(dashboard)/businesses/new/page.tsx
This pull request refactors the NewBusiness form to generate unique IDs for directors and shareholders. Previously, the form would insert a new director or shareholder with a default schema. Now, the form generates a unique ID using the crypto.randomUUID() function and assigns it to the new director or shareholder. This ensures that each director and shareholder has a unique identifier.
=> Refactor NewBusiness form to generate unique IDs for directors and shareholders

src/app/(dashboard)/account-requests/page.tsx, src/app/admin/(dashboard)/account-requests/[id]/page.tsx, src/lib/search.ts
This pull request refactors the search functionality to include the "accountName" property. It modifies the `AccountRequests` and `BusinessAccountRequests` components to include "accountName" in the search filter. Additionally, it adds a new utility function `multiKeySearch` that allows for searching multiple properties with a single search value.
=> Refactor search functionality to include "accountName" property

src/app/(dashboard)/account-requests/page.tsx, src/app/(dashboard)/users/page.tsx, src/app/admin/(dashboard)/account-requests/[id]/page.tsx, src/app/admin/(dashboard)/users/(tabs)/BusinessUsers.tsx, src/app/admin/(dashboard)/users/(tabs)/Users.tsx, src/app/admin/(dashboard)/users/[id]/business/[userId]/page.tsx, src/app/admin/(dashboard)/users/[id]/business/page.tsx, src/app/admin/(dashboard)/users/modal.tsx, src/app/admin/(dashboard)/users/page.tsx, src/lib/hooks/admins.ts, src/lib/hooks/requests.ts, src/lib/schema.ts, src/ui/components/Buttons/button.module.scss, src/ui/components/Buttons/index.tsx
This pull request includes refactoring of user-related components and schemas. It improves the code structure and organization, making it more maintainable and scalable.
This pull request merges the 'develop' branch of the repository into the 'gilead/acct-corrections' branch. It brings in the latest changes from the 'develop' branch to the 'gilead/acct-corrections' branch.
Refactor user table in dashboard to display last login time and handle null values
=> Refactor user-related components and schemas

package.json, src/app/(dashboard)/notifications/(tabs)/All.tsx, src/app/(dashboard)/notifications/(tabs)/Read.tsx, src/app/(dashboard)/notifications/(tabs)/Unread.tsx, src/app/(dashboard)/notifications/page.tsx, src/app/admin/(dashboard)/notifications/page.tsx, src/app/layout.tsx, src/env.ts, src/lib/hooks/notification.tsx, src/lib/hooks/notifications.ts, src/lib/static.tsx, src/lib/store/notification.ts, src/lib/store/user.ts, src/ui/components/Header/index.tsx, src/ui/components/NotificationProvider/index.tsx, src/ui/components/NotificationRow/index.tsx, yarn.lock
This pull request includes several changes. First, the AccountCard component has been refactored to align and justify the SeeAll link on the right. Second, a new environment variable, NEXT_PUBLIC_AUTH_BASE_URL, has been added to the env.ts file. Third, the User interface in user.ts has been updated to include the companyId property. Additionally, new components and hooks have been added to handle notifications, including the NotificationProvider component, ReadNotification, AllNotification, and UnreadNotification components, and the useUserNotifications hook. The ScrollArea component in the All, Read, and Unread notification tabs has been refactored to include paddingRight of 20px. Finally, the PaginationComponent rendering in the All and Unread notification tabs has been simplified.
=> Refactor AccountCard component, add new environment variable, and update user interface

src/app/(dashboard)/notifications/(tabs)/All.tsx, src/app/(dashboard)/notifications/(tabs)/Read.tsx, src/app/(dashboard)/notifications/page.tsx, src/app/admin/(dashboard)/notifications/(tabs)/All.tsx, src/app/admin/(dashboard)/notifications/(tabs)/Read.tsx, src/app/admin/(dashboard)/notifications/(tabs)/Unread.tsx, src/app/admin/(dashboard)/notifications/page.tsx, src/lib/hooks/notifications.ts, src/ui/components/Header/index.tsx, src/ui/components/Navbar/index.tsx, src/ui/components/NotificationRow/index.tsx
- Introduce admin notification hooks and components, enhancing the handling of read, unread, and all notifications. Refactor notification fetching logic for improved performance and usability.
- Added notification socket to admin.
- Enhanced the loading, empty states as well on the business, admin side.
=> Implement admin notification system and refactor fetching logic

src/app/(dashboard)/debit-requests/new/modal.tsx, src/lib/schema.ts, src/ui/components/Header/index.tsx
- Improve the Header and UserHeader components to handle total counts more gracefully, 
- Update the Indicator color and processing state based on avaliability of unread notification,
- Set a default avatar count of 0 when undefined.
- Changed avatar (notification count text) text color to --prune-text-gray-800.
- Set the default domain value in the newBusiness schema to 'https://', and 
- Add a searchable feature to the destination country input in the DebitRequestModal.
=> Enhance UI components and add searchable feature to form input

src/app/(dashboard)/debit-requests/new/modal.tsx, src/lib/hooks/accounts.ts, src/ui/components/SingleAccount/Individual.tsx, src/ui/components/SingleAccount/company.tsx, src/ui/components/SingleAccount/index.tsx, src/ui/components/SingleAccount/sendMoneyModal.tsx
Introduce account validation with user feedback in SendMoneyModal and DebitRequestModal, while adjusting modal sizes for better responsiveness.
=> Add account validation feature and responsive adjustments in modals

src/lib/hooks/notification.tsx
Ensure that previous notifications are cleared before displaying new ones to improve user experience.
=> Refactor notification handling to clear previous notifications

src/app/admin/(dashboard)/accounts/page.tsx, src/app/admin/(dashboard)/settings/(tabs)/logs.tsx, src/ui/components/Header/index.tsx
Introduce CSV export for logs and refactor the Logs component for improved structure and readability.
=> Enhance log management with CSV export functionality

src/app/(dashboard)/accounts/default/page.tsx, src/app/(dashboard)/transactions/(tabs)/Accounts.tsx, src/app/(dashboard)/transactions/(tabs)/IssuedAccounts.tsx, src/app/(dashboard)/transactions/(tabs)/Payouts.tsx, src/app/admin/(dashboard)/accounts/[id]/page.tsx, src/app/admin/(dashboard)/businesses/[id]/default/page.tsx, src/app/admin/(dashboard)/businesses/[id]/payout/page.tsx, src/app/admin/(dashboard)/requests/[...slug]/page.tsx, src/lib/hooks/requests.ts, src/ui/components/SingleAccount/index.tsx, src/ui/components/TableRows/index.tsx
Improve transaction handling and pagination across account components, update total calculations, and ensure consistent display of last activity. Add admin checks for the "Send Money" button visibility.
=> Enhance transaction handling and refactor account components

src/app/admin/(dashboard)/businesses/[id]/(tabs)/accounts.tsx, src/app/admin/(dashboard)/businesses/[id]/default/page.tsx, src/app/admin/(dashboard)/businesses/[id]/payout/page.tsx, src/app/admin/(dashboard)/dashboard/page.tsx, src/app/admin/(dashboard)/transactions/page.tsx, src/lib/hooks/transactions.ts
This pull request includes several changes to improve the handling of business and payout account transactions in the admin dashboard. The most important changes include updating links to include account IDs, adding new hooks for fetching transactions, and enhancing the UI for displaying transaction data.
* `src/app/admin/(dashboard)/businesses/[id]/(tabs)/accounts.tsx`: Updated links to include `accountId` for default and payout accounts. ([src/app/admin/(dashboard)/businesses/[id]/(tabs)/accounts.tsxL209-R209](diffhunk://#diff-ecea906546ee920a246738b064bbf6b031a02e4a22b9487fe97443a9fbb639bcL209-R209), [src/app/admin/(dashboard)/businesses/[id]/(tabs)/accounts.tsxL221-R221](diffhunk://#diff-ecea906546ee920a246738b064bbf6b031a02e4a22b9487fe97443a9fbb639bcL221-R221))
* …
=> Transactions Fixes

src/app/admin/(dashboard)/users/(tabs)/Users.tsx, src/app/admin/(dashboard)/users/page.tsx, src/lib/axios.ts, src/lib/hooks/admins.ts, src/lib/hooks/notifications.ts, src/ui/components/Header/index.tsx, src/ui/components/Navbar/index.tsx
- This pull request includes several commits that refactor the code in the Navbar components. 
- The first commit adds an Axios instance creation utility with request interceptors for authentication and staging header. 
- The second commit refactors the Axios instance creation and updates the API calls in the admin hooks for improved readability and maintainability. 
- The third commit refactors the notification handling in the Navbar components to clear the notification badge and updates the revalidate functions to be asynchronous. 
- The fourth commit updates the stage handling in the UserHeader component and improves the notification marking in the Navbar. 
These changes aim to improve the code structure and make it easier to understand and maintain.
=> Refactor API calls and notification handling in Navbar components

src/ui/components/SingleAccount/index.tsx
Centralize axios requests in DefaultAccountHead by utilizing a dedicated axios instance, simplifying the request structure and improving maintainability.
=> Refactor axios requests in DefaultAccountHead to use centralized instance

src/app/(dashboard)/accounts/page.tsx, src/app/(dashboard)/debit-requests/new/modal.tsx, src/ui/components/SingleAccount/(tabs)/SendMoney.tsx, src/ui/components/SingleAccount/Individual.tsx, src/ui/components/SingleAccount/company.tsx, src/ui/components/SingleAccount/index.tsx
This pull request introduces several changes to the `Accounts` page and related components. The primary focus is on integrating a new `SendMoney` component and adjusting existing components to support this new feature.
* [`src/app/(dashboard)/accounts/page.tsx`](diffhunk://#diff-47241ad0d4a63dfdf671c40775330632050156220422fd6764662d207ba2ddc8R60): Added the `SendMoney` component and integrated it with the `Accounts` page. This includes new state hooks for managing the send money modal and actions. [[1]](diffhunk://#diff-47241ad0d4a63dfdf671c40775330632050156220422fd6764662d207ba2ddc8R60) [[2]](diffhunk://#diff-47241ad0d4a63dfdf671c40775330632050156220422fd6764662d207ba2ddc8R106-R107) [[3]](diffhunk://#diff-47241ad0d4a63dfdf671c40775330632050156220422fd6764662d207ba2ddc8R486-R491)
* …
=> Send Money/Debit Request in Account Page; Validation debounce delay

src/lib/schema.ts, src/ui/components/SingleAccount/Individual.tsx, src/ui/components/SingleAccount/company.tsx
This pull request includes several changes to the validation schemas and UI components for handling individual and company account forms. The most important changes involve making the `bankAddress` field optional in the validation schemas and updating the UI components to handle the new optional fields and improve form handling.
* [`src/lib/schema.ts`](diffhunk://#diff-788cfa8897b3d37a0d726b64c66fa8700807c7439dd0be3f73198ef6e0cbb8a0L540-R541): Updated the `sendMoneyIndividualValidate` and `sendMoneyCompanyValidate` schemas to make the `bankAddress` field optional. [[1]](diffhunk://#diff-788cfa8897b3d37a0d726b64c66fa8700807c7439dd0be3f73198ef6e0cbb8a0L540-R541) [[2]](diffhunk://#diff-788cfa8897b3d37a0d726b64c66fa8700807c7439dd0be3f73198ef6e0cbb8a0L555-R557)
* …
=> Form field disabling based on validation results and cleaning up unused imports

src/app/(dashboard)/accounts/[id]/page.tsx, src/app/(dashboard)/debit-requests/new/modal.tsx, src/app/(dashboard)/page.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsx, src/app/admin/(dashboard)/businesses/[id]/page.tsx, src/lib/hooks/businesses.ts, src/ui/components/Header/index.tsx, src/ui/components/SingleAccount/(tabs)/Transactions.tsx, src/ui/components/SingleAccount/Individual.tsx, src/ui/components/SingleAccount/company.tsx, src/ui/components/SingleAccount/index.tsx, src/ui/components/SingleAccount/sendMoneyModal.tsx
This pull request includes several changes across multiple files to enhance the functionality and improve the user experience of the dashboard and business management components. The most important changes include adding new state variables, modifying existing components to support new features, and updating services and business logic.
* [`src/app/(dashboard)/debit-requests/new/modal.tsx`](diffhunk://#diff-0afbea0a3add5f4548ef755c3c3f55efaf6810f82b4c1caac285dc0c08df3cb7R90): Added `showBadge` state variable and updated the component to show/hide the badge based on certain actions. [[1]](diffhunk://#diff-0afbea0a3add5f4548ef755c3c3f55efaf6810f82b4c1caac285dc0c08df3cb7R90) [[2]](diffhunk://#diff-0afbea0a3add5f4548ef755c3c3f55efaf6810f82b4c1caac285dc0c08df3cb7R111) …
=> Send Money for Biz Dashboard, Restricting Live Stage toggling and Admin enabling live mode service

src/app/(dashboard)/accounts/page.tsx, src/app/(dashboard)/page.tsx, src/app/(dashboard)/payouts/(tabs)/Account.tsx, src/ui/components/Cards/AccountCard.tsx
This pull request introduces several changes to the `Accounts` and `Home` components, as well as the `AccountCard` component, to add revalidation functionality and improve user experience. The most important changes include adding the `revalidate` property to various components and updating the `AccountCard` component to handle refresh actions.
Enhancements to revalidation functionality:
* [`src/app/(dashboard)/accounts/page.tsx`](diffhunk://#diff-47241ad0d4a63dfdf671c40775330632050156220422fd6764662d207ba2ddc8L94-R98): Added `revalidate` property to the `useUserDefaultAccount` hook and passed it to the `AccountCard` component. [[1]](diffhunk://#diff-47241ad0d4a63dfdf671c40775330632050156220422fd6764662d207ba2ddc8L94-R98) [[2]](diffhunk://#diff-47241ad0d4a63dfdf671c40775330632050156220422f …
=> Refresh Account Balance

src/app/(dashboard)/accounts/[id]/page.tsx, src/app/(dashboard)/accounts/default/page.tsx, src/app/(dashboard)/payouts/[id]/account/page.tsx, src/app/admin/(dashboard)/accounts/[id]/page.tsx, src/app/admin/(dashboard)/businesses/[id]/default/page.tsx, src/app/admin/(dashboard)/businesses/[id]/payout/page.tsx, src/app/admin/(dashboard)/businesses/accounts/[id]/page.tsx, src/app/admin/(dashboard)/payouts/[id]/account/page.tsx, src/lib/hooks/accounts.ts, src/ui/components/SingleAccount/index.tsx
This pull request introduces several changes to the `src/app` and `src/lib/hooks` directories, focusing on adding a `revalidate` function to various account-related components and hooks. Additionally, it refactors some components to use a new `AccountInfo` component for displaying account details.
* Added `revalidate` prop to `SingleAccount`, `SingleDefaultAccount`, and `SingleUserPayoutAccount` components to enable refreshing account data. ([src/app/(dashboard)/accounts/[id]/page.tsxR275](diffhunk://#diff-8318c0e4d6cd6cd445f3876fe02a04ae4a19a43dc27543ab8e92e20eb5f8b268R275), [src/app/(dashboard)/accounts/default/page.tsxL60-R64](diffhunk://#diff-dc17512fcdfcc3ce94567dafb4008325edea2557d496c7a22c2c2faf676d90b0L60-R64), [src/app/(dashboard)/payouts/[id]/account/page.tsxL66-R66](diffhunk://# …
=> Implemented Refreshing of Account Balance & New Account Details Design

src/app/(dashboard)/users/modal.tsx, src/app/(dashboard)/users/page.tsx, src/app/admin/(dashboard)/businesses/[id]/page.tsx, src/app/admin/(dashboard)/users/(tabs)/Users.tsx, src/app/admin/(dashboard)/users/[id]/business/page.tsx, src/app/admin/(dashboard)/users/modal.tsx, src/lib/schema.ts
This pull request includes several changes across multiple files to enhance user management functionality and improve code quality. The most important changes include adding a new optional `text` property to the `ModalComponent`, updating the `Users` page to include role-based filtering, and adding a new modal for inviting users to a business.
Enhancements to `ModalComponent`:
* [`src/app/(dashboard)/users/modal.tsx`](diffhunk://#diff-fb7c6535f82c188cfcdf15a4da95df4ce03d38e3b2fbc1e563746ae8b735cbf4R29): Added a new optional `text` property to `ModalProps` and updated the component to use this property for displaying custom text. [[1]](diffhunk://#diff-fb7c6535f82c188cfcdf15a4da95df4ce03d38e3b2fbc1e563746ae8b735cbf4R29) [[2]](diffhunk://#diff-fb7c6535f82c188cfcdf15a4da95df4ce03d38e3b2fbc1e5 …
=> Admin can add a user to a business.

src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsx, src/app/admin/(dashboard)/businesses/[id]/page.tsx
This pull request includes several changes to the `business.tsx` file in the admin dashboard. The changes primarily focus on enhancing the `Business` and `ContactInfo` components by adding new imports, updating component props, and introducing new functionalities.
Key changes include:
* Added `Popover`, `PopoverDropdown`, `PopoverTarget`, and `Stack` from Mantine to enhance the UI components. ([src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsxR9-R13](diffhunk://#diff-04b1e1c4bd7cc06f3e68e416025f74275d0c354e4ea6cd9c17f287cf7948ad05R9-R13))
* Added `SingleBizMeta` from the `businesses` hooks to handle business metadata. ([src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsxR25](diffhunk://#diff-04b1e1c4bd7cc06f3e68e416025f74275d0c354e4ea6cd9c17f287cf7948ad05R25))
* …
=> Add functionality to send activation links to users via alternate email

.vscode/settings.json, src/app/(dashboard)/settings/(tabs)/keys.tsx, src/app/admin/(dashboard)/businesses/[id]/(tabs)/documents.tsx, src/app/admin/(dashboard)/businesses/new/BasicInfo.tsx, src/app/admin/(dashboard)/businesses/new/Documents.tsx, src/lib/hooks/businesses.ts, src/lib/schema.ts
This pull request includes several changes to the business document management system and minor updates to the spelling settings and country list. The most important changes are grouped into two themes: updates to the document management system and miscellaneous improvements.
* Added a new field `companyPOAUrl` to various components and schemas to support the upload of Corporate Proof of Address documents. (`src/app/admin/(dashboard)/businesses/[id]/(tabs)/documents.tsx`, `src/lib/hooks/businesses.ts`, `src/lib/schema.ts`) ([src/app/admin/(dashboard)/businesses/[id]/(tabs)/documents.tsxL61-R61](diffhunk://#diff-7b662d834deac3765a4321b431087745bf9413e1822af1c334c3714bdca03718L61-R61), [src/app/admin/(dashboard)/businesses/[id]/(tabs)/documents.tsxR301](diffhunk://#diff-7b662d834deac3765a432 …
=> Updates to the document management system and miscellaneous improvements

src/app/admin/(dashboard)/requests/[...slug]/page.tsx, src/app/admin/(dashboard)/requests/drawer.tsx, src/lib/hooks/requests.ts
This pull request includes several changes aimed at improving the handling of API requests and removing redundant code. The most important changes include the creation of a centralized Axios instance, the removal of hardcoded URLs and authorization headers, and the addition of a new property to the `DebitRequest` interface.
* `src/app/admin/(dashboard)/requests/[...slug]/page.tsx`: Removed imports for `axios` and `Cookies`, and created an Axios instance using `createAxiosInstance` for API requests. This change also removes hardcoded URLs and authorization headers from the `axios.post` calls. ([src/app/admin/(dashboard)/requests/[...slug]/page.tsxL4-L7](diffhunk://#diff-c9a370b461026fc2e0740a29a32a60dc2a9ef7f9b8c95b8104654c710f457941L4-L7), …
=> Approving or Rejecting debit request with correct staging env

src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsx
This pull request includes a change to the `Business` component in the `business.tsx` file to update the Axios instance being used.
* `src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsx`: Changed the Axios instance from "accounts" to "auth" to ensure the correct authentication context is used. ([src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsxL55-R55](diffhunk://#diff-04b1e1c4bd7cc06f3e68e416025f74275d0c354e4ea6cd9c17f287cf7948ad05L55-R55))
=> Refactor: Update the Axios instance being used

src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsx, src/app/admin/(dashboard)/businesses/new/BasicInfo.tsx, src/lib/hooks/businesses.ts, src/lib/schema.ts
This pull request introduces the "Trading Name" field to the business management module. The changes span multiple files to ensure the new field is integrated consistently across the application.
Key changes include:
* `src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsx`: Added `tradingName` to the business data and updated the `BasicInformation` component to include a new input for "Trading Name". ([src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsxR75](diffhunk://#diff-04b1e1c4bd7cc06f3e68e416025f74275d0c354e4ea6cd9c17f287cf7948ad05R75), [src/app/admin/(dashboard)/businesses/[id]/(tabs)/business.tsxR215-R227](diffhunk://#diff-04b1e1c4bd7cc06f3e68e416025f74275d0c354e4ea6cd9c17f287cf7948ad05R215-R227))
* [`src/app/admin/(dashboard)/businesses/new/BasicInfo.tsx`](diffh …
=> Introducing the "Trading Name" field to the business management module

src/app/admin/(dashboard)/dashboard/page.tsx, src/app/admin/(dashboard)/transactions/page.tsx
This pull request includes several changes to the `src/app/admin/(dashboard)/dashboard/page.tsx` and `src/app/admin/(dashboard)/transactions/page.tsx` files to enhance the transaction management features. The most significant changes involve importing new components, updating link paths, and adding a transaction drawer.
Enhancements to transaction management:
* [`src/app/admin/(dashboard)/dashboard/page.tsx`](diffhunk://#diff-29045d5a6b386cd851924d9529872aa51e1c722185d46751425a5412e55640eaR62-R70): Imported `Transaction` from `@/lib/store/transaction` and `TransactionDrawer` from `@/app/(dashboard)/transactions/drawer`.
* [`src/app/admin/(dashboard)/dashboard/page.tsx`](diffhunk://#diff-29045d5a6b386cd851924d9529872aa51e1c722185d46751425a5412e55640eaL327-R330): Updated the link path to …
=> Dashboard Transactions

src/app/(dashboard)/debit-requests/new/modal.tsx, src/app/admin/(dashboard)/payouts/[id]/account/page.tsx, src/lib/schema.ts, src/lib/utils.ts, src/ui/components/SingleAccount/(tabs)/SendMoney.tsx, src/ui/components/SingleAccount/Individual.tsx, src/ui/components/SingleAccount/company.tsx
This pull request includes several changes to improve the handling of whitespace in IBAN and BIC values across different components and functions. Additionally, there are some minor refactorings and updates to hooks and schema validation.
* [`src/app/(dashboard)/debit-requests/new/modal.tsx`](diffhunk://#diff-0afbea0a3add5f4548ef755c3c3f55efaf6810f82b4c1caac285dc0c08df3cb7L45-R45): Added `removeWhitespace` function to clean up IBAN and BIC values before validation and form submission. [[1]](diffhunk://#diff-0afbea0a3add5f4548ef755c3c3f55efaf6810f82b4c1caac285dc0c08df3cb7L45-R45) [[2]](diffhunk://#diff-0afbea0a3add5f4548ef755c3c3f55efaf6810f82b4c1caac285dc0c08df3cb7R112-R117) [[3]](diffhunk://#diff-0afbea0a3add5f4548ef755c3c3f55efaf6810f82b4c1caac285dc0c08df3cb7L168-R173) …
=> Trimming an iban and bic for debit requests and send money 

src/app/admin/(dashboard)/accounts/(tabs)/default.tsx, src/app/admin/(dashboard)/accounts/(tabs)/issued.tsx, src/app/admin/(dashboard)/accounts/(tabs)/payout.tsx, src/app/admin/(dashboard)/accounts/[id]/default/page.tsx, src/app/admin/(dashboard)/accounts/[id]/payout/page.tsx, src/app/admin/(dashboard)/accounts/page.tsx, src/app/admin/(dashboard)/dashboard/page.tsx, src/app/admin/(dashboard)/transactions/page.tsx, src/lib/axios.ts, src/lib/hooks/useAxios.ts, src/lib/utils.ts, src/ui/components/AccountInfoCards/FlowCard.tsx, src/ui/components/AccountInfoCards/FlowChart.tsx, src/ui/components/AccountInfoCards/StatusCard.tsx, src/ui/components/AccountInfoCards/StatusChart.tsx, src/ui/components/AccountInfoCards/index.tsx, src/ui/components/AccountInfoCards/util.tsx, src/ui/components/SingleAccount/index.tsx
This pull request includes several changes to the `src/app/admin/(dashboard)/accounts/[id]` and related files to enhance the functionality of business accounts and payout accounts. The most important changes include the addition of new components, updates to existing components, and improvements in the Axios hook for API requests.
* `src/app/admin/(dashboard)/accounts/[id]/default/page.tsx`: Added the `BusinessDefaultAccount` component to handle the default account view with various hooks for fetching account data and transactions. ([src/app/admin/(dashboard)/accounts/[id]/default/page.tsxR1-R167](diffhunk://#diff-55dd24db91a58c38c3a0f533c5622b1ea8390af00984621377a19abfc5eb4e34R1-R167))
* `src/app/admin/(dashboard)/accounts/[id]/payout/page.tsx`: Added the `BusinessPayoutAccount` …
=> New Admin Account UI Refactor

src/app/admin/(dashboard)/payouts/(tabs)/Users.tsx, src/app/admin/(dashboard)/payouts/[id]/account/page.tsx, src/app/admin/(dashboard)/transactions/page.tsx, src/lib/hooks/accounts.ts, src/lib/utils.ts, src/ui/components/SingleAccount/(tabs)/Analytics.tsx, src/ui/components/SingleAccount/index.tsx
This pull request includes several changes aimed at improving code readability, functionality, and performance in the admin payouts and transactions components. The most important changes include the addition of a utility function to calculate total pages, refactoring of data fetching logic, and enhanced documentation.
* [`src/lib/utils.ts`](diffhunk://#diff-da10bcc7d8dff796f50c9358a7268eb5abd2c50f460aecc4b2be1c691a966224R166-R172): Added a new utility function `calculateTotalPages` to simplify the calculation of total pages based on limit and total values.
* [`src/app/admin/(dashboard)/payouts/(tabs)/Users.tsx`](diffhunk://#diff-4b9b58858a85671af76a9d5dcd6412eef58663b0dc1b5249b34ffe1f4ad3d3cdL161-R162): Replaced manual total page calculation with the new `calculateTotalPages` utility …
=> Fix for a payout account's transaction; util function to handle total page in pagination

src/app/admin/(dashboard)/transactions/page.tsx
This pull request includes several changes to the `src/app/admin/(dashboard)/accounts/[id]` and related files to enhance the functionality of business accounts and payout accounts. The most important changes include the addition of new components, updates to existing components, and improvements in the Axios hook for API requests.
* `src/app/admin/(dashboard)/accounts/[id]/default/page.tsx`: Added the `BusinessDefaultAccount` component to handle the default account view with various hooks for fetching account data and transactions. ([src/app/admin/(dashboard)/accounts/[id]/default/page.tsxR1-R167](diffhunk://#diff-55dd24db91a58c38c3a0f533c5622b1ea8390af00984621377a19abfc5eb4e34R1-R167))
* `src/app/admin/(dashboard)/accounts/[id]/payout/page.tsx`: Added the `BusinessPayoutAccount` …
=> New Account UI

src/app/(dashboard)/account-requests/drawer.tsx, src/app/admin/(dashboard)/accounts/(tabs)/default.tsx, src/app/admin/(dashboard)/accounts/(tabs)/issued.tsx, src/app/admin/(dashboard)/accounts/(tabs)/payout.tsx, src/app/admin/(dashboard)/accounts/[id]/default/page.tsx, src/app/admin/(dashboard)/accounts/[id]/payout/page.tsx, src/app/admin/(dashboard)/accounts/page.tsx, src/lib/axios.ts, src/lib/hooks/accounts.ts, src/lib/hooks/useAxios.ts, src/ui/components/AccountInfoCards/FlowCard.tsx, src/ui/components/AccountInfoCards/FlowChart.tsx, src/ui/components/AccountInfoCards/StatusCard.tsx, src/ui/components/AccountInfoCards/StatusChart.tsx, src/ui/components/AccountInfoCards/index.tsx, src/ui/components/AccountInfoCards/util.tsx
This pull request includes several significant changes across multiple files to enhance the functionality and user interface of the account management system. The most important changes include the addition of new components for displaying account information, the introduction of a custom hook for handling Axios requests, and updates to existing components and hooks to improve data handling and presentation.
* [`src/ui/components/AccountInfoCards/FlowCard.tsx`](diffhunk://#diff-fa19b0ada0f24dd48af7efd114f91d2f1778f6b94a9e843f91a082135761c677R1-R34): Added a new `FlowCard` component to display financial flow information, including total amounts and percentage changes.
* [`src/ui/components/AccountInfoCards/FlowChart.tsx`](diffhunk://#diff-5c37232452cfb56f397b67a52b4aee1eaec5f45bf1054de2bef6 …
=> Account Cards; useAxios hook

package.json, src/app/(dashboard)/accounts/default/page.tsx, src/app/(dashboard)/page.tsx, src/app/(dashboard)/payouts/(tabs)/PayoutTransactions/(tabs)/All.tsx, src/app/(dashboard)/payouts/(tabs)/PayoutTransactions/(tabs)/Cancelled.tsx, src/app/(dashboard)/payouts/(tabs)/Requests/drawer.tsx, src/app/(dashboard)/payouts/PayoutDrawer.tsx, src/app/(dashboard)/transactions/(tabs)/Accounts.tsx, src/app/(dashboard)/transactions/(tabs)/Payouts.tsx, src/app/(dashboard)/transactions/[accountId]/page.tsx, src/app/(dashboard)/transactions/drawer.tsx, src/app/(dashboard)/transactions/receipt/page.tsx, src/app/admin/(dashboard)/accounts/[id]/default/page.tsx, src/app/admin/(dashboard)/accounts/[id]/page.tsx, src/app/admin/(dashboard)/accounts/[id]/payout/page.tsx, src/app/admin/(dashboard)/dashboard/page.tsx, src/app/admin/(dashboard)/requests/(tabs)/payouts/drawer.tsx, src/lib/hooks/receipt.ts, src/lib/hooks/transactions.ts, src/lib/hooks/useTrxAnalytics.ts, src/lib/utils.ts, src/ui/components/Badge/index.tsx, src/ui/components/ChartLoading/index.tsx, src/ui/components/Charts/index.tsx, src/ui/components/SingleAccount/(tabs)/Analytics.tsx, src/ui/components/SingleAccount/(tabs)/Transactions.tsx, src/ui/components/SingleAccount/index.tsx, src/ui/components/TableRows/index.tsx, src/ui/components/TransactionReceipt/index.tsx, yarn.lock
This pull request includes several changes to the payout and transaction components, focusing on refactoring and improving the receipt details functionality. The most significant changes include adding the `isUser` property to various components, refactoring the receipt details logic into a reusable hook, and updating the admin dashboard to handle default account transactions.
Refactoring and Improvements:
* Added `isUser` property to multiple components in the payout and transaction tabs to improve user-specific functionalities. (`src/app/(dashboard)/payouts/(tabs)/PayoutTransactions/(tabs)/All.tsx` [[1]](diffhunk://#diff-36fab4135b2391b96d58c5424b65caa05d66b74295d218d361fefe559e379ab8R138) `src/app/(dashboard)/payouts/(tabs)/PayoutTransactions/(tabs)/Cancelled.tsx` …
=> Added Narration to receipt; Added link to senderName on Business & Payout Account Transaction Table; removed routing for dummy Iban

src/app/admin/(dashboard)/transactions/(tabs)/business.tsx, src/app/admin/(dashboard)/transactions/(tabs)/issued.tsx, src/app/admin/(dashboard)/transactions/(tabs)/payout.tsx, src/app/admin/(dashboard)/transactions/page.tsx, src/assets/countries.json, src/lib/hooks/infoDetails.ts, src/lib/hooks/param.ts, src/lib/hooks/transactions.ts, src/lib/schema.ts, src/ui/components/SingleAccount/Individual.tsx, src/ui/components/SingleAccount/company.tsx, src/ui/components/TableRows/index.tsx
This pull request includes significant updates to the transaction tabs in the admin dashboard, focusing on implementing new components, hooks, and utilities to enhance the functionality and user experience. The changes involve the addition of new transaction handling components and hooks for various transaction types, such as business, issued, and payout transactions.
Enhancements to transaction tabs:
* [`src/app/admin/(dashboard)/transactions/(tabs)/business.tsx`](diffhunk://#diff-192a8d0c5ac6582e0fdec2f596a59fbb0a086ef72b1e8b85e1d264490559fa1dR1-R149): Added components for handling business account transactions, including filters, search input, pagination, and table components.
* [`src/app/admin/(dashboard)/transactions/(tabs)/issued.tsx`](diffhunk://#diff-9437225057630d226931139ad19e730 …
=> Updated countries for send money; implemented backend search for admin/transactions business account tab

src/ui/components/AccountInfoCards/FlowChart.tsx, src/ui/components/AccountInfoCards/StatusCard.tsx, src/ui/components/AccountInfoCards/StatusChart.tsx, src/ui/components/AccountInfoCards/index.tsx, src/ui/components/AccountInfoCards/util.tsx
This pull request includes several changes to the `AccountInfoCards` components to add support for an `accountType` prop and improve the codebase by removing unused imports and updating component properties. The most important changes include adding the `accountType` prop to multiple components, modifying the `ChartHeader` component to utilize this new prop, and cleaning up unused imports.
* [`src/ui/components/AccountInfoCards/FlowChart.tsx`](diffhunk://#diff-5c37232452cfb56f397b67a52b4aee1eaec5f45bf1054de2bef64cca3d691975R18-R25): Added `accountType` prop to the `FlowChart` component and updated its usage in the component. [[1]](diffhunk://#diff-5c37232452cfb56f397b67a52b4aee1eaec5f45bf1054de2bef64cca3d691975R18-R25) [[2]](diffhunk://#diff-5c37232452cfb56f397b67a52b4aee1eaec5f45bf1054de2 …
=> Handled tooltip; removed dummy data for FlowChart

src/ui/components/Valentine/index.tsx
This pull request includes a small change to the `src/ui/components/Valentine/index.tsx` file. The change updates the default title text in the `Valentine` component.
* [`src/ui/components/Valentine/index.tsx`](diffhunk://#diff-3dcf13cc5e9716aeb296d6012a4c8b98ed4101630b1155703bc488966594e652L28-R28): Changed the default title from "Happy Valentine" to "Happy Valentine's Day".
=> Update Valentine's Day title for improved clarity and user experience

src/app/(dashboard)/page.tsx, src/lib/hooks/roles.ts
This pull request introduces new hooks for fetching user roles and deactivated user roles using Axios in the `src/lib/hooks/roles.ts` file. Additionally, it defines TypeScript interfaces for `Role` and `Permission`. Also added the transactions tables to business dashboard. 
New hooks for fetching roles:
* [`useUserRoles`](diffhunk://#diff-44893c2d7bd54b437750de1a81ad829ca95e43564318827802b0e487148e575eR1-R45): A hook to fetch active user roles with customizable parameters.
* [`useDeactivatedUserRoles`](diffhunk://#diff-44893c2d7bd54b437750de1a81ad829ca95e43564318827802b0e487148e575eR1-R45): A hook to fetch deactivated user roles with customizable parameters.
TypeScript interfaces:
* [`Role`](diffhunk://#diff-44893c2d7bd54b437750de1a81ad829ca95e43564318827802b0e487148e575eR1-R45): Defines …
=> Added Own, Issued, and Payout Account Transactions to Business Dashboard

src/app/(dashboard)/roles/(tabs)/active.tsx, src/app/(dashboard)/roles/(tabs)/deactivated.tsx, src/app/(dashboard)/roles/DeactivateRoleModal.tsx, src/app/(dashboard)/roles/new/page.tsx, src/app/(dashboard)/roles/page.tsx, src/lib/hooks/roles.ts, src/lib/schema.ts
This pull request includes several significant changes to the roles management functionality in the dashboard. The changes include adding new components, updating existing ones, and enhancing the user experience with new features such as role deactivation and pagination.
* [`src/app/(dashboard)/roles/(tabs)/active.tsx`](diffhunk://#diff-020f536b0c6a1c4917a2a662cc207cef7e3b328ced5a146e40918108cb678e7dR1-R173): Implemented the `ActiveRoles` component to display active roles with search, pagination, and deactivation functionality.
* [`src/app/(dashboard)/roles/(tabs)/deactivated.tsx`](diffhunk://#diff-a7515e8bd71fc1e99a90668cded65cf5dcb4e78cc3c393eac451530b9d4f7c95R1-R130): Implemented the `DeactivatedRoles` component to display deactivated roles with search and pagination functionality.
* …
=> Business Roles & Permissions

src/app/(dashboard)/users/modal.tsx, src/lib/hooks/roles.ts
Refactor the role selection in the modal to group roles by type, enhancing the data structure for better organization and usability.
=> Group roles by Application/Created Roles when inviting a user

src/app/admin/(dashboard)/users/(tabs)/Users.tsx, src/app/admin/(dashboard)/users/modal.tsx
Update the admin user creation process to include password and improve the import structure of modal components.
=> Refactor admin user creation and enhance modal imports

src/app/(dashboard)/payouts/(tabs)/Inquiries.tsx, src/app/(dashboard)/payouts/(tabs)/Requests/AllPayoutRequests.tsx, src/app/(dashboard)/payouts/(tabs)/Requests/PendingRequests.tsx, src/app/(dashboard)/users/(tabs)/activeRole.tsx, src/app/(dashboard)/users/(tabs)/activeUsers.tsx, src/lib/schema.ts
- Introduce validation for editing users in the active users component. This resolves the validation error thrown when updating users with no first and last name since names are not updated.
- With no flow for assigning user to role, Assign User menu button under Active Roles table was commented out.
=> Add user editing validation and clean up unused code

src/app/(dashboard)/transactions/drawer.tsx, src/lib/hooks/receipt.ts, src/lib/hooks/transactions.ts, src/ui/components/SingleAccount/(defaultTabs)/DefaultDocuments.tsx, src/ui/components/SingleAccount/(tabs)/Transactions.tsx, src/ui/components/SingleAccount/Individual.tsx, src/ui/components/SingleAccount/company.tsx, src/ui/components/SingleAccount/sendMoneyModal.tsx, src/ui/components/TransactionReceipt/index.tsx
Reverts Prune-finance/Apas-client#275
=> Revert "Emma/gbp account implementation"

src/ui/components/SingleAccount/(tabs)/Transactions.tsx
**What does this PR do?**
- Updates GBP statement url
=> Fix: Gbp statement url update

src/ui/components/SingleAccount/(defaultTabs)/DefaultAccountDetails.tsx, src/ui/components/SingleAccount/(tabs)/SendMoney.tsx, src/ui/components/SingleAccount/index.tsx
- Remove console.log statement in SendMoney component
- Fix indentation in CopyButton value prop
- Improve readability of AccountDetails props by breaking into multiple lines
- Update API endpoint to handle both accountNumber and walletId cases
=> refactor: remove debug logs and improve code formatting

src/app/(dashboard)/accounts/default/[id]/page.tsx, src/ui/components/Filter/index.tsx, src/ui/components/SingleAccount/(tabs)/Transactions.tsx
- Reorder currency parameter in account page for consistency
- Remove debug console.log from transactions component
- Enhance transaction input labels to support GHS currency
- Improve URL parameter handling in filter component to preserve existing params
=> refactor(accounts): improve URL handling and transaction input labels
